In [4]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2, employee3]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)

Employee 1: 
Enter name: Murali
Family Members: 4
Employee Salary: 45000
Employee Department: Technical
Employee 2: 
Enter name: Krishna
Family Members: 4
Employee Salary: 50000
Employee Department: Non-Technical
Full Time Employee 1: 
Enter name: Pranay
Family Members: 5
Employee Salary: 100000
Employee Department: Software

Number of employees:  3
Avg salary is : 65000.0


In [4]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)

[16.41117175  8.26009752 11.96067288 18.18757295  3.57834967  1.62513528
  6.35828943  1.51358888 14.12630632  3.88060967 17.47795237 18.33521254
  5.37282516  1.47450245  6.05347153 10.09096409  9.20144949 12.46663379
  8.04874045 16.82444727]




[[16.41117175  8.26009752 11.96067288 18.18757295  3.57834967]
 [ 1.62513528  6.35828943  1.51358888 14.12630632  3.88060967]
 [17.47795237 18.33521254  5.37282516  1.47450245  6.05347153]
 [10.09096409  9.20144949 12.46663379  8.04874045 16.82444727]]


[[16.41117175  8.26009752 11.96067288  0.          3.57834967]
 [ 1.62513528  6.35828943  1.51358888  0.          3.88060967]
 [17.47795237  0.          5.37282516  1.47450245  6.05347153]
 [10.09096409  9.20144949 12.46663379  8.04874045  0.        ]]
